{
 "title": "PF Stats",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "server", "label": "server" }
  ]
 },
 "panels": [
  {
   "title": "PF Throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "target": "alias(scaleToSeconds(scale(nonNegativeDerivative(pf.$server.counts.In4_bytes_Pass), 8), 1), 'IPv4 Bytes In')"
    },
    {
     "target": "alias(scaleToSeconds(scale(nonNegativeDerivative(pf.$server.counts.Out4_bytes_Pass), 8), 1), 'IPv4 Bytes Out')"
    },
    {
     "target": "alias(pf.$server.counts.current_entries, 'States')"
    }
   ]
  },
  {
   "title": "PF Packets",
   "type": "graph",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "target": "alias(nonNegativeDerivative(scaleToSeconds(pf.$server.counts.In4_packets_Pass, 1)), 'Pass In')"
    },
    {
     "target": "alias(nonNegativeDerivative(scaleToSeconds(pf.$server.counts.Out4_packets_Pass, 1)), 'Pass Out')"
    },
    {
     "target": "alias(nonNegativeDerivative(scaleToSeconds(pf.$server.counts.In4_packets_Block, 1)), 'Block In')"
    },
    {
     "target": "alias(nonNegativeDerivative(scaleToSeconds(pf.$server.counts.Out4_packets_Block, 1)), 'Block Out')"
    }
   ]
  },
  {
   "title": "PF Misc",
   "type": "graph",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "target": "alias(nonNegativeDerivative(scaleToSeconds(pf.$server.counts.fragment, 1)), 'frag')"
    },
    {
     "target": "alias(nonNegativeDerivative(scaleToSeconds(pf.$server.counts.congestion, 1)), 'cong')"
    },
    {
     "target": "alias(nonNegativeDerivative(scaleToSeconds(pf.$server.counts.ip-option, 1)), 'ipopt')"
    },
    {
     "target": "alias(nonNegativeDerivative(scaleToSeconds(pf.$server.counts.proto-cksum, 1)), 'csum')"
    },
    {
     "target": "alias(nonNegativeDerivative(scaleToSeconds(pf.$server.counts.state-mismatch, 1)), 'mism')"
    },
    {
     "target": "alias(nonNegativeDerivative(scaleToSeconds(pf.$server.counts.match, 1)), 'match')"
    }
   ]
  },
  {
   "title": "PF States",
   "type": "graph",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short", "label": "states/s" }
   ],
   "targets": [
    {
     "target": "alias(nonNegativeDerivative(scaleToSeconds(pf.$server.counts.inserts, 1)), 'inserts')"
    },
    {
     "target": "alias(nonNegativeDerivative(scaleToSeconds(pf.$server.counts.removals, 1)), 'removals')"
    },
    {
     "target": "alias(nonNegativeDerivative(scaleToSeconds(pf.$server.counts.searches, 1)), 'searches')"
    }
   ]
  }
 ]
}