#!/bin/sh

daemon="/opt/pf-graphite/pflog_graphite_poller"

. /etc/rc.d/rc.subr

rc_bg=YES
rc_reload=NO
pexp="python ${daemon}.*"

# This is an ugly hack because killing the underlying tcpdump
# child processes proved to be another hack.
rc_stop() {
    /usr/bin/pkill tcpdump || true
    /usr/bin/pkill pflog_graphite_poller || true
}

rc_cmd $1
